### ISSUE TITLE
Question: why consider only 7 bits per byte for an unsigned int?

### ISSUE THREAD

**Issue by pfac** [multiformats/go-varint#5]
Hey there,

So I was working on attempting to port this lib into another language, and I saw that `UvarintSize` is dividing the number of bits by 7 to compute the size in bytes of a 64-bit unsigned integer (https://github.com/multiformats/go-varint/blob/99465703c4a9cf53a0235e52608cb055e9d39c29/varint.go#L19).

I'm trying to understand why did you consider 7 bits per byte, instead of 8 bits per byte.

Thanks in advance

**Comment by ribasushi** [comment]
A varint is somewhat like utf8: all "wire-bytes" but the last have the highest bit set, to indicate "more is coming". Hence the "wiresize" of a varint representation is the "payload" divided into chunks of 7 bits.

For reference this is what an actual varint encoder looks like: https://golang.org/src/encoding/binary/varint.go?s=1611:1652#L31
```
func PutUvarint(buf []byte, x uint64) int {
	i := 0
	for x >= 0x80 {
		buf[i] = byte(x) | 0x80
		x >>= 7
		i++
	}
	buf[i] = byte(x)
	return i + 1
}
```

**Comment by pfac** [comment]
Got it. Thanks for clearing that up.

**Comment by vmx** [comment]
@pfac just a note that this kind of varint encoding also goes by the name [LEB128](https://en.wikipedia.org/wiki/LEB128), so there might already be an implementation available for your language of choice.
