### ISSUE TITLE
This package allows for 10 byte varints.

### ISSUE THREAD

**Issue by Stebalien** [multiformats/go-varint#8]
See https://github.com/multiformats/unsigned-varint/blob/master/README.md#practical-maximum-of-9-bytes-for-security.

This says that a varint can have at most 9 bytes. In go, a varint can have 10 bytes as long as the last byte is exactly `0x1`. This allow specifying 64bit numbers.

I'm happy to change this implementation, but I want to make sure nobody knows of anything it might break.

**Comment by Stebalien** [comment]
Hm. Unfortunately, in theory, Filecoin could use this extra bit for addresses. We'll need to figure that out first.

**Comment by ribasushi** [comment]
@Stebalien is the title mis-phrased? This package rejects 10 byte varints as of https://github.com/multiformats/go-varint/pull/6/files ...?

**Comment by Stebalien** [comment]
Uh, yeah... you're right. Nvm.
